name: Test & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Check formatting
      run: |
        go fmt ./...
        goimports -l . | tee /dev/stderr | (! read)

    - name: Tidy modules
      run: |
        go mod tidy
        git diff --exit-code

    - name: Run tests
      run: go test ./...
